### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by jvir**
Translations update from [Weblate](http://trans.etranslator.eu/projects/foundry-cypher-system/system/) for Foundry Cypher System/System.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by NiceTSY** [comment]
Pardon my stupidity but what is that?

**Comment by mrkwnzl** [comment]
I was asked about a Spanish translation a while ago and I reached out again. This seems to be a translation service, which wants to create a Spanish json, so that it can be translated using that service. I’m not familiar with that, as of yet

**Comment by NiceTSY** [comment]
Oh great!
My bad for not knowing such an easy system to do translation!

**Comment by jvir** [comment]
Sorry, it is a system that we use in the Spanish community of foundry to translate systems (a continuous translation tool) that facilitates the maintenance of the same and among other things sends the PR automatically.

ParvusDomus is in charge of this translation since we created the project this morning.

This is the initial PR sent automatically by the tool and at the moment it is empty.

**Comment by mrkwnzl** [comment]
Thanks for your work! I didn’t know Weblate (but to be fair, I haven’t looked too deep into translations, yet), so that might be super useful. Let me know if I can help with anything. The translation strings might undergo some changes, still. Would that be problematic for Weblate?

**Comment by jvir** [comment]
Thanks for your work! I didn’t know Weblate (but to be fair, I haven’t looked too deep into translations, yet), so that might be super useful. Let me know if I can help with anything. The translation strings might undergo some changes, still. Would that be problematic for Weblate?

**Pull request merged**
