### PR TITLE
Localisation

### PR DESCRIPTION
**Pull request by NiceTSY**

### CODE REVIEW

**Comment by NiceTSY** [comment]
Added localisation to your fantastic system if you need it.

**Comment by mrkwnzl** [comment]
Wow, that’s awesome! I was planning on adding localisations for some time now, and that’s a good start! Thanks! Could you create a pull request without the changes to the character sheet size and markers, though?

The character sheet sizes need a different solution, and more changes, as the height of the editor is hard coded right now. The size is chosen in this way because this allows for people with lower resolutions to use the sheets as well. I can’t make it dynamic in size, as of yet, because the editor is a bit wonky then (that’s even a problem in the 5e system, and those guys really know what they are doing).

As for the markers, I can’t see what changes you made, since the .db file is gibberish. I have Foundry running on a Linux machine now as well and I haven’t seen any problems with the current release. I’m a bit reluctant to merge something without knowing what has been changed.

**Comment by mrkwnzl** [comment]
Ah, I see the problem with the markers. I’ll correct that separately.

**Comment by NiceTSY** [comment]
Hi, sorry I was away from my computer after the pull yesterday.
Yes, I will withdraw those sheet modifications and only push the localisation part :) 
I know they were hardcoded and I only pushed the width to 640px instead of 600px, so it should not have changed that much for lower resolutions I think.

For the marker, it was just the icon path for the Token.

**Comment by mrkwnzl** [comment]
> Hi, sorry I was away from my computer after the pull yesterday.

No worries, it’s not urgent.

> Yes, I will withdraw those sheet modifications and only push the localisation part :)

Awesome! Thanks for the great work!

> I know they are hardcoded and I only made the width to 640px instead of 600px, so it should not have changed that much for lower resolutions I think.

The issue is with the height, not with the width. I’ve gotten reports from people with a vertical resolution of 700px (which is the lowest end that Foundry officially supports, I believe). You have to subtract the height of the macro bar and the map selector, which are about 100px, I think. I then subtracted a few more pixels, to be sure, so the current height is the highest I can go while it’s hard coded without causing issues. I’ve never been contacted that the sheet is too small, so I’ve never followed this further, but I’ll look into a better solution.

Best, of course, would be if the sheet size could be dynamic, but I’m also thinking about a way to hide the upper half of the sheet for more space of the lower part. I’ll play around with a dynamic width, but hard coded height as well and see if that causes issues.

> For the marker, it was just the icon path for the Token, but I can revert this as well if you want.

All right, I’ll backup by .db file, just in case, so you can keep it in.

I have a bit time at the weekend to merge and test it. Thanks again! That’s really helpful!

**Comment by NiceTSY** [comment]
I understand the issue with height. I agree that a dynamic sheet will be even better ^^
I can see if I can pull up something too.

In fact, height is not that important for "bigger" language just the width to fully show some element without making the sheet looking weird. I changed the height too because I wanted to keep your sheet ratio at the beginning.
**Currently:**
image

**With the 640px width (and 40px for the "is a" and "who" part):**
image

> All right, I’ll backup by .db file, just in case, so you can keep it in.

No worries :) 

> I have a bit time at the weekend to merge and test it. Thanks again! That’s really helpful!

Tell me how it went!

**Comment by mrkwnzl** [comment]
> In fact, height is not that important for "bigger" language just the width to fully show some element without making the sheet looking weird. I changed the height too because I wanted to keep your sheet ratio at the beginning.

I’ll see what I can do about that. One important thing for that is to keep the non-breaking spaces where I had them. That will prevent the line breaks and the other elements will adjust dynamically, mostly.

**Comment by mrkwnzl** [comment]
Closing this PR. I made another branch for localization and pulled your branch into there. I made two changes: (1) The identifier should be the name of the system, so I changed all the different ones to “CYPHERSYSTEM.” (2) I was getting some errors due to the periods as delimiters of the identifiers. I changed all of them to a single value.

Next up would be translations of the macros and system settings. I won’t get around that before next weekend, but if you want to get on with it, let me know.

**Pull request closed without merging**
