### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by jvir**
Translations update from [Weblate](http://trans.etranslator.eu/projects/foundry-cypher-system/system/) for Foundry Cypher System/System.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by mrkwnzl** [comment]
Just as a quick update: I’ll wait with this until we have figured out how to implement translations for macros, especially since this also overwrites the French translation, which is currently maintained differently.

Would it be possible to only commit the Spanish translation?

**Comment by jvir** [comment]
Yes, it is possible, actually the French translation was made by another user on his own initiative. I just sent him a message.

Sorry for the inconvenience.

**Comment by mrkwnzl** [comment]
No inconvenience at all, I’m grateful that people want to help. Send them my way, if anyone wants to help. We can coordinate better, then. You can also reach me on Discord (mrkwnzl#7407).

**Comment by NiceTSY** [comment]
Hey guys!
Yes, sorry that's me who tried your platform out of curiosity. So no needs to keep the French translation I am updating it with other means :)

**Pull request closed without merging**
